name: Auto Create Pull Request

on:
  push:
    branches:
      - develop  # Trigger the workflow on pushes to the develop branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated changes"
        branch: "auto-pr-branch-from-develop"  # Customize this branch name
        base: "develop"  # Set the base branch to develop
        title: "Automated Pull Request from Develop"
        body: "This pull request contains automated changes from the develop branch."
        labels: "automated, ci"
        assignees: "your-github-username"
        reviewers: "reviewer-username"
        delete-branch: true
        draft: false
